### ISSUE TITLE
vue exemple

### ISSUE THREAD

**Issue by frederic117** [tamasszoke/neat-rtc#20]
I try to launch the vue exemple but i get this error..
Can you help me please :)

internal/modules/cjs/loader.js:800
    throw err;
    ^

Error: Cannot find module 'D:\Dev\neat-rtc\examples\clients\vue\build\webpack.dev.conf.js'
Require stack:
- D:\Dev\neat-rtc\examples\clients\vue\node_modules\webpack-cli\bin\utils\convert-argv.js
- D:\Dev\neat-rtc\examples\clients\vue\node_modules\webpack-dev-server\bin\webpack-dev-server.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
    at Function.Module._load (internal/modules/cjs/loader.js:690:27)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at WEBPACK_OPTIONS (D:\Dev\neat-rtc\examples\clients\vue\node_modules\webpack-cli\bin\utils\convert-argv.js:114:13)
    at requireConfig (D:\Dev\neat-rtc\examples\clients\vue\node_modules\webpack-cli\bin\utils\convert-argv.js:116:6)
    at D:\Dev\neat-rtc\examples\clients\vue\node_modules\webpack-cli\bin\utils\convert-argv.js:123:17
    at Array.forEach (<anonymous>)
    at module.exports (D:\Dev\neat-rtc\examples\clients\vue\node_modules\webpack-cli\bin\utils\convert-argv.js:121:15)
    at Object.<anonymous> (D:\Dev\neat-rtc\examples\clients\vue\node_modules\webpack-dev-server\bin\webpack-dev-server.js:84:40) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'D:\\Dev\\neat-rtc\\examples\\clients\\vue\\node_modules\\webpack-cli\\bin\\utils\\convert-argv.js',
    'D:\\Dev\\neat-rtc\\examples\\clients\\vue\\node_modules\\webpack-dev-server\\bin\\webpack-dev-server.js'
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vue@1.0.0 dev: `webpack-dev-server --inline --progress --config build/webpack.dev.conf.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vue@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by tamasszoke** [comment]
Hi frederic117, I tested it and the error occurred, so I updated the Vue example to the newest version.
Please download the updated version and check the examples section of the updated readme as well.

**Comment by frederic117** [comment]
great thanks a lot :)
